import {
  Shield,
  Users,
  UserCog,
  MenuSquare,
  KeyRound,
  Building2,
  Briefcase,
  UserPlus,
  CalendarDays,
  Clock,
  CheckCircle2,
  CalendarRange,
  Wallet,
  LayoutDashboard,
  FileText,
  Activity,
  FolderCog,
  Settings,
  CalendarClock,
  CalendarHeart,
  FileClock,
  NotebookTabs,
  CalendarCheck,
  ArrowUpDown,
  ClipboardList,
  UserCheck,
  WalletCards,
  FileSpreadsheet,
  DollarSign,
} from "lucide-react";

export const iconMap = {
  shield: Shield,
  users: Users,
  "user-lock": UserCog,
  list: MenuSquare,
  settings: Settings,
  key: KeyRound,
  "file-spreadsheet": FileSpreadsheet,
  building: Building2,
  briefcase: Briefcase,
  employee: UserPlus,
  settings: Settings,
  "wallet-cards": WalletCards,
  attendance: CalendarDays,
  clock: CalendarClock,
  "dollar-sign": DollarSign,
  check: CheckCircle2,
  balance: ArrowUpDown,
  leave: CalendarRange,
  wallet: Wallet,
  "layout-dashboard": LayoutDashboard,
  file: FileText,
  activity: Activity,
  "folder-cog": FolderCog,
  holiday: CalendarHeart,
  "request-status": FileClock,
  "attendance-status": NotebookTabs,
  "leave-types": CalendarCheck,
  "my-requests": ClipboardList,
  "my-approvals": UserCheck,
};
